#!/bin/bash
#
# postfix2     Postfix2 Mail Transfer Agent
#
# chkconfig: 2345 80 30
# description: Postfix is a Mail Transport Agent, which is the program \
#              that moves mail from one machine to another.
# processname: master
# pidfile: /var/spool/postfix2/pid/master.pid
# config: /etc/postfix2/main.cf
# config: /etc/postfix2/master.cf
#
# Based on startup script from Simon J Mudd <sjmudd@pobox.com>
# 25/02/99: Mostly s/sendmail/postfix/g by John A. Martin <jam@jamux.com>
# 23/11/00: Changes & suggestions by Ajay Ramaswamy <ajayr@bigfoot.com>
# 20/01/01: Changes to fall in line with RedHat 7.0 style
# 23/02/01: Fix a few untidy problems with help from Daniel Roesen.
# 01/11/05: Modified for Second Instance by Mike Chirico <mchirico@gmail.com>
#    (http://souptonuts.sourceforge.net/postfix_sbr.html)

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

[ -x /usr/sbin/postfix ] || exit 0
[ -d /etc/postfix2 ] || exit 0
[ -d /var/spool/postfix2 ] || exit 0

RETVAL=0

start() {
	# Start daemons.
	echo -n "Starting postfix: "
	alias_database=$(postconf -c /etc/postfix2 -h alias_database 2>/dev/null)
	RETVAL=1
	[ -z "$alias_database" ] && {
	    failure "determination of alias_database"
	    echo
	    return 0	    
	}
	/usr/sbin/postalias -c /etc/postfix2 ${alias_database//,} 2>/dev/null
	RETVAL=$?
	[ $RETVAL -ne 0 ] && {
	    failure "postalias $alias_database"
	    echo
	    return 0	    
	}
	/usr/sbin/postfix -c /etc/postfix2 start 2>/dev/null 1>&2 && success || failure
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/postfix2
        echo
	return $RETVAL
}

stop() {
        # Stop daemons.
	echo -n "Shutting down postfix: "
	/usr/sbin/postfix -c /etc/postfix2 stop 2>/dev/null 1>&2 && success || failure
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/postfix2
	echo
	return $RETVAL
}

reload() {
	echo -n "Reloading postfix: "
	/usr/sbin/postfix -c /etc/postfix2 reload 2>/dev/null 1>&2 && success || failure
	RETVAL=$?
	echo
	return $RETVAL
}

abort() {
	/usr/sbin/postfix -c /etc/postfix2 abort 2>/dev/null 1>&2 && success || failure
	return $?
}

flush() {
	/usr/sbin/postfix -c /etc/postfix2 flush 2>/dev/null 1>&2 && success || failure
	return $?
}

check() {
	/usr/sbin/postfix -c /etc/postfix2 check 2>/dev/null 1>&2 && success || failure
	return $?
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  reload)
	reload
	;;
  abort)
	abort
	;;
  flush)
	flush
	;;
  check)
	check
	;;
  status)
  	status master
	;;
  condrestart)
	[ -f /var/lock/subsys/postfix2 ] && restart || :
	;;
  *)
	echo "Usage: postfix {start|stop|restart|reload|abort|flush|check|status|condrestart}"
	exit 1
esac

exit $?
